---
 - name: update cache
   apt: update_cache=yes

 - name: install required packages
   apt: name={{ item }} state=present
   with_items:
       - git
       - synaptic
       - openjdk-8-jdk

 - name: install packages for crypted removeable devices
   apt: name={{ item }} state=present
   with_items:
       - cryptsetup

 -  name: load crypt module
    args:
      executable: /bin/bash
    shell: |
      sudo modprobe dm-crypt 
