# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.synced_folder "../", "/test"
  config.vm.provision "shell", inline: <<-SHELL
     cd /test
     sudo ./init
     sudo ./run
  SHELL
end
