---
 - name: install packages for crypted removeable devices
   apt: name={{ item }} state=present
   with_items:
       - cryptsetup

 -  name: load crypt module
    args:
      executable: /bin/bash
    shell: |
      sudo modprobe dm-crypt
