---
- hosts: all
  become: yes
  become_method: sudo


  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - docker

  tasks:
   - include: base.yml
   - include: Dev/network.yml
   - include: Dev/tools.yml
   - include: Dev/virtual.yml
#   - include: office.yml
#   - include: SocEnt/media.yml
#   - include: SocEnt/social.yml


  vars:
    docker_daemon_dns: ["172.21.33.161"]
    docker_daemon_storage_driver: aufs
